version: "3.8"

services:
  postgres:
    image: postgres
    container_name: speaker-port-postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    container_name: csv-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
